# @Author: ZhanYu
# @Email: 2833171898@qq.com
# @Date:   2026-06-03 13:29:52
# @Last Modified by:   ZhanYu
# @Last Modified time: 2026-06-10 23:41:58
# @Github: https://github.com/luigits
# @blog: https://luigits.github.io/

name: Excavator


on:
  workflow_dispatch:      # 支持 GitHub Actions 页面手动触发
  schedule:
    - cron: '0 0 * * *'  # 每周一 UTC 03:00 执行（可按需调整）

permissions:
  contents: write

jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Excavate
      uses: ScoopInstaller/GithubActions@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
